package com.zil.cherubim.model;

public class Access {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access.access_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String accessName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access.id
     *
     * @return the value of access.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access.id
     *
     * @param id the value for access.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access.access_name
     *
     * @return the value of access.access_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getAccessName() {
        return accessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access.access_name
     *
     * @param accessName the value for access.access_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setAccessName(String accessName) {
        this.accessName = accessName == null ? null : accessName.trim();
    }
}