package com.zil.cherubim.model;

public class CharacterSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_skill.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer characterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer skillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_skill.skill_level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer skillLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_skill.id
     *
     * @return the value of character_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_skill.id
     *
     * @param id the value for character_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_skill.character_id
     *
     * @return the value of character_skill.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_skill.character_id
     *
     * @param characterId the value for character_skill.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_skill.skill_id
     *
     * @return the value of character_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_skill.skill_id
     *
     * @param skillId the value for character_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_skill.skill_level
     *
     * @return the value of character_skill.skill_level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getSkillLevel() {
        return skillLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_skill.skill_level
     *
     * @param skillLevel the value for character_skill.skill_level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillLevel(Integer skillLevel) {
        this.skillLevel = skillLevel;
    }
}