package com.zil.cherubim.model;

public class CharacterJob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_job.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_job.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer characterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_job.job_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer jobId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_job.id
     *
     * @return the value of character_job.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_job.id
     *
     * @param id the value for character_job.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_job.character_id
     *
     * @return the value of character_job.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_job.character_id
     *
     * @param characterId the value for character_job.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_job.job_id
     *
     * @return the value of character_job.job_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_job.job_id
     *
     * @param jobId the value for character_job.job_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }
}