package com.zil.cherubim.model;

import java.util.ArrayList;
import java.util.List;

public class CharacterExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public CharacterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCharacterNameIsNull() {
            addCriterion("character_name is null");
            return (Criteria) this;
        }

        public Criteria andCharacterNameIsNotNull() {
            addCriterion("character_name is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterNameEqualTo(String value) {
            addCriterion("character_name =", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotEqualTo(String value) {
            addCriterion("character_name <>", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameGreaterThan(String value) {
            addCriterion("character_name >", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameGreaterThanOrEqualTo(String value) {
            addCriterion("character_name >=", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameLessThan(String value) {
            addCriterion("character_name <", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameLessThanOrEqualTo(String value) {
            addCriterion("character_name <=", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameLike(String value) {
            addCriterion("character_name like", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotLike(String value) {
            addCriterion("character_name not like", value, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameIn(List<String> values) {
            addCriterion("character_name in", values, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotIn(List<String> values) {
            addCriterion("character_name not in", values, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameBetween(String value1, String value2) {
            addCriterion("character_name between", value1, value2, "characterName");
            return (Criteria) this;
        }

        public Criteria andCharacterNameNotBetween(String value1, String value2) {
            addCriterion("character_name not between", value1, value2, "characterName");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andLevelIsNull() {
            addCriterion("level is null");
            return (Criteria) this;
        }

        public Criteria andLevelIsNotNull() {
            addCriterion("level is not null");
            return (Criteria) this;
        }

        public Criteria andLevelEqualTo(Integer value) {
            addCriterion("level =", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotEqualTo(Integer value) {
            addCriterion("level <>", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThan(Integer value) {
            addCriterion("level >", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("level >=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThan(Integer value) {
            addCriterion("level <", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelLessThanOrEqualTo(Integer value) {
            addCriterion("level <=", value, "level");
            return (Criteria) this;
        }

        public Criteria andLevelIn(List<Integer> values) {
            addCriterion("level in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotIn(List<Integer> values) {
            addCriterion("level not in", values, "level");
            return (Criteria) this;
        }

        public Criteria andLevelBetween(Integer value1, Integer value2) {
            addCriterion("level between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("level not between", value1, value2, "level");
            return (Criteria) this;
        }

        public Criteria andExperienceIsNull() {
            addCriterion("experience is null");
            return (Criteria) this;
        }

        public Criteria andExperienceIsNotNull() {
            addCriterion("experience is not null");
            return (Criteria) this;
        }

        public Criteria andExperienceEqualTo(Integer value) {
            addCriterion("experience =", value, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceNotEqualTo(Integer value) {
            addCriterion("experience <>", value, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceGreaterThan(Integer value) {
            addCriterion("experience >", value, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceGreaterThanOrEqualTo(Integer value) {
            addCriterion("experience >=", value, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceLessThan(Integer value) {
            addCriterion("experience <", value, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceLessThanOrEqualTo(Integer value) {
            addCriterion("experience <=", value, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceIn(List<Integer> values) {
            addCriterion("experience in", values, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceNotIn(List<Integer> values) {
            addCriterion("experience not in", values, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceBetween(Integer value1, Integer value2) {
            addCriterion("experience between", value1, value2, "experience");
            return (Criteria) this;
        }

        public Criteria andExperienceNotBetween(Integer value1, Integer value2) {
            addCriterion("experience not between", value1, value2, "experience");
            return (Criteria) this;
        }

        public Criteria andCharacterImageIsNull() {
            addCriterion("character_image is null");
            return (Criteria) this;
        }

        public Criteria andCharacterImageIsNotNull() {
            addCriterion("character_image is not null");
            return (Criteria) this;
        }

        public Criteria andCharacterImageEqualTo(String value) {
            addCriterion("character_image =", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageNotEqualTo(String value) {
            addCriterion("character_image <>", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageGreaterThan(String value) {
            addCriterion("character_image >", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageGreaterThanOrEqualTo(String value) {
            addCriterion("character_image >=", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageLessThan(String value) {
            addCriterion("character_image <", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageLessThanOrEqualTo(String value) {
            addCriterion("character_image <=", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageLike(String value) {
            addCriterion("character_image like", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageNotLike(String value) {
            addCriterion("character_image not like", value, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageIn(List<String> values) {
            addCriterion("character_image in", values, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageNotIn(List<String> values) {
            addCriterion("character_image not in", values, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageBetween(String value1, String value2) {
            addCriterion("character_image between", value1, value2, "characterImage");
            return (Criteria) this;
        }

        public Criteria andCharacterImageNotBetween(String value1, String value2) {
            addCriterion("character_image not between", value1, value2, "characterImage");
            return (Criteria) this;
        }

        public Criteria andHitpointsIsNull() {
            addCriterion("hitpoints is null");
            return (Criteria) this;
        }

        public Criteria andHitpointsIsNotNull() {
            addCriterion("hitpoints is not null");
            return (Criteria) this;
        }

        public Criteria andHitpointsEqualTo(Integer value) {
            addCriterion("hitpoints =", value, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsNotEqualTo(Integer value) {
            addCriterion("hitpoints <>", value, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsGreaterThan(Integer value) {
            addCriterion("hitpoints >", value, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("hitpoints >=", value, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsLessThan(Integer value) {
            addCriterion("hitpoints <", value, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsLessThanOrEqualTo(Integer value) {
            addCriterion("hitpoints <=", value, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsIn(List<Integer> values) {
            addCriterion("hitpoints in", values, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsNotIn(List<Integer> values) {
            addCriterion("hitpoints not in", values, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsBetween(Integer value1, Integer value2) {
            addCriterion("hitpoints between", value1, value2, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andHitpointsNotBetween(Integer value1, Integer value2) {
            addCriterion("hitpoints not between", value1, value2, "hitpoints");
            return (Criteria) this;
        }

        public Criteria andManapointsIsNull() {
            addCriterion("manapoints is null");
            return (Criteria) this;
        }

        public Criteria andManapointsIsNotNull() {
            addCriterion("manapoints is not null");
            return (Criteria) this;
        }

        public Criteria andManapointsEqualTo(Integer value) {
            addCriterion("manapoints =", value, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsNotEqualTo(Integer value) {
            addCriterion("manapoints <>", value, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsGreaterThan(Integer value) {
            addCriterion("manapoints >", value, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("manapoints >=", value, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsLessThan(Integer value) {
            addCriterion("manapoints <", value, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsLessThanOrEqualTo(Integer value) {
            addCriterion("manapoints <=", value, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsIn(List<Integer> values) {
            addCriterion("manapoints in", values, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsNotIn(List<Integer> values) {
            addCriterion("manapoints not in", values, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsBetween(Integer value1, Integer value2) {
            addCriterion("manapoints between", value1, value2, "manapoints");
            return (Criteria) this;
        }

        public Criteria andManapointsNotBetween(Integer value1, Integer value2) {
            addCriterion("manapoints not between", value1, value2, "manapoints");
            return (Criteria) this;
        }

        public Criteria andGoldIsNull() {
            addCriterion("gold is null");
            return (Criteria) this;
        }

        public Criteria andGoldIsNotNull() {
            addCriterion("gold is not null");
            return (Criteria) this;
        }

        public Criteria andGoldEqualTo(Integer value) {
            addCriterion("gold =", value, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldNotEqualTo(Integer value) {
            addCriterion("gold <>", value, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldGreaterThan(Integer value) {
            addCriterion("gold >", value, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldGreaterThanOrEqualTo(Integer value) {
            addCriterion("gold >=", value, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldLessThan(Integer value) {
            addCriterion("gold <", value, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldLessThanOrEqualTo(Integer value) {
            addCriterion("gold <=", value, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldIn(List<Integer> values) {
            addCriterion("gold in", values, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldNotIn(List<Integer> values) {
            addCriterion("gold not in", values, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldBetween(Integer value1, Integer value2) {
            addCriterion("gold between", value1, value2, "gold");
            return (Criteria) this;
        }

        public Criteria andGoldNotBetween(Integer value1, Integer value2) {
            addCriterion("gold not between", value1, value2, "gold");
            return (Criteria) this;
        }

        public Criteria andStatpointsIsNull() {
            addCriterion("statpoints is null");
            return (Criteria) this;
        }

        public Criteria andStatpointsIsNotNull() {
            addCriterion("statpoints is not null");
            return (Criteria) this;
        }

        public Criteria andStatpointsEqualTo(Integer value) {
            addCriterion("statpoints =", value, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsNotEqualTo(Integer value) {
            addCriterion("statpoints <>", value, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsGreaterThan(Integer value) {
            addCriterion("statpoints >", value, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("statpoints >=", value, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsLessThan(Integer value) {
            addCriterion("statpoints <", value, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsLessThanOrEqualTo(Integer value) {
            addCriterion("statpoints <=", value, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsIn(List<Integer> values) {
            addCriterion("statpoints in", values, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsNotIn(List<Integer> values) {
            addCriterion("statpoints not in", values, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsBetween(Integer value1, Integer value2) {
            addCriterion("statpoints between", value1, value2, "statpoints");
            return (Criteria) this;
        }

        public Criteria andStatpointsNotBetween(Integer value1, Integer value2) {
            addCriterion("statpoints not between", value1, value2, "statpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsIsNull() {
            addCriterion("skillpoints is null");
            return (Criteria) this;
        }

        public Criteria andSkillpointsIsNotNull() {
            addCriterion("skillpoints is not null");
            return (Criteria) this;
        }

        public Criteria andSkillpointsEqualTo(Integer value) {
            addCriterion("skillpoints =", value, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsNotEqualTo(Integer value) {
            addCriterion("skillpoints <>", value, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsGreaterThan(Integer value) {
            addCriterion("skillpoints >", value, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsGreaterThanOrEqualTo(Integer value) {
            addCriterion("skillpoints >=", value, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsLessThan(Integer value) {
            addCriterion("skillpoints <", value, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsLessThanOrEqualTo(Integer value) {
            addCriterion("skillpoints <=", value, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsIn(List<Integer> values) {
            addCriterion("skillpoints in", values, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsNotIn(List<Integer> values) {
            addCriterion("skillpoints not in", values, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsBetween(Integer value1, Integer value2) {
            addCriterion("skillpoints between", value1, value2, "skillpoints");
            return (Criteria) this;
        }

        public Criteria andSkillpointsNotBetween(Integer value1, Integer value2) {
            addCriterion("skillpoints not between", value1, value2, "skillpoints");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table character
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}