package com.zil.cherubim.model;

public class Character {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.character_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String characterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.gender
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.experience
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.character_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String characterImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.hitpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer hitpoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.manapoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer manapoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.gold
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer gold;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.statpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer statpoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character.skillpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer skillpoints;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.id
     *
     * @return the value of character.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.id
     *
     * @param id the value for character.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.character_name
     *
     * @return the value of character.character_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getCharacterName() {
        return characterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.character_name
     *
     * @param characterName the value for character.character_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterName(String characterName) {
        this.characterName = characterName == null ? null : characterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.gender
     *
     * @return the value of character.gender
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.gender
     *
     * @param gender the value for character.gender
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.level
     *
     * @return the value of character.level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.level
     *
     * @param level the value for character.level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.experience
     *
     * @return the value of character.experience
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.experience
     *
     * @param experience the value for character.experience
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.character_image
     *
     * @return the value of character.character_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getCharacterImage() {
        return characterImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.character_image
     *
     * @param characterImage the value for character.character_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterImage(String characterImage) {
        this.characterImage = characterImage == null ? null : characterImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.hitpoints
     *
     * @return the value of character.hitpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getHitpoints() {
        return hitpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.hitpoints
     *
     * @param hitpoints the value for character.hitpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setHitpoints(Integer hitpoints) {
        this.hitpoints = hitpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.manapoints
     *
     * @return the value of character.manapoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getManapoints() {
        return manapoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.manapoints
     *
     * @param manapoints the value for character.manapoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setManapoints(Integer manapoints) {
        this.manapoints = manapoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.gold
     *
     * @return the value of character.gold
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getGold() {
        return gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.gold
     *
     * @param gold the value for character.gold
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setGold(Integer gold) {
        this.gold = gold;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.statpoints
     *
     * @return the value of character.statpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getStatpoints() {
        return statpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.statpoints
     *
     * @param statpoints the value for character.statpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setStatpoints(Integer statpoints) {
        this.statpoints = statpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character.skillpoints
     *
     * @return the value of character.skillpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getSkillpoints() {
        return skillpoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character.skillpoints
     *
     * @param skillpoints the value for character.skillpoints
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillpoints(Integer skillpoints) {
        this.skillpoints = skillpoints;
    }
}