package com.zil.cherubim.model;

public class CharacterRace {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_race.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_race.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer characterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_race.race_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer raceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_race.id
     *
     * @return the value of character_race.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_race.id
     *
     * @param id the value for character_race.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_race.character_id
     *
     * @return the value of character_race.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_race.character_id
     *
     * @param characterId the value for character_race.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_race.race_id
     *
     * @return the value of character_race.race_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getRaceId() {
        return raceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_race.race_id
     *
     * @param raceId the value for character_race.race_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setRaceId(Integer raceId) {
        this.raceId = raceId;
    }
}