package com.zil.cherubim.model;

public class CharacterStats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_stats.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_stats.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer characterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_stats.stat_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer statId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column character_stats.points
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_stats.id
     *
     * @return the value of character_stats.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_stats.id
     *
     * @param id the value for character_stats.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_stats.character_id
     *
     * @return the value of character_stats.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_stats.character_id
     *
     * @param characterId the value for character_stats.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_stats.stat_id
     *
     * @return the value of character_stats.stat_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getStatId() {
        return statId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_stats.stat_id
     *
     * @param statId the value for character_stats.stat_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setStatId(Integer statId) {
        this.statId = statId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column character_stats.points
     *
     * @return the value of character_stats.points
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column character_stats.points
     *
     * @param points the value for character_stats.points
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPoints(Integer points) {
        this.points = points;
    }
}