package com.zil.cherubim.model;

public class Job {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String jobDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.job_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String jobImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.id
     *
     * @return the value of job.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.id
     *
     * @param id the value for job.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_name
     *
     * @return the value of job.job_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_name
     *
     * @param jobName the value for job.job_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_description
     *
     * @return the value of job.job_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getJobDescription() {
        return jobDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_description
     *
     * @param jobDescription the value for job.job_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setJobDescription(String jobDescription) {
        this.jobDescription = jobDescription == null ? null : jobDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.job_image
     *
     * @return the value of job.job_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getJobImage() {
        return jobImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.job_image
     *
     * @param jobImage the value for job.job_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setJobImage(String jobImage) {
        this.jobImage = jobImage == null ? null : jobImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job.is_available
     *
     * @return the value of job.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job.is_available
     *
     * @param isAvailable the value for job.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setIsAvailable(Integer isAvailable) {
        this.isAvailable = isAvailable;
    }
}