package com.zil.cherubim.model;

public class JobsSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs_skill.job_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jobs_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer skillId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs_skill.id
     *
     * @return the value of jobs_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs_skill.id
     *
     * @param id the value for jobs_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs_skill.job_id
     *
     * @return the value of jobs_skill.job_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs_skill.job_id
     *
     * @param jobId the value for jobs_skill.job_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setJobId(Integer jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jobs_skill.skill_id
     *
     * @return the value of jobs_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jobs_skill.skill_id
     *
     * @param skillId the value for jobs_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }
}