package com.zil.cherubim.model;

import java.util.ArrayList;
import java.util.List;

public class OperatorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public OperatorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Integer value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Integer value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Integer value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Integer value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Integer value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Integer> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Integer> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Integer value1, Integer value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Integer value1, Integer value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameIsNull() {
            addCriterion("operator_user_name is null");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameIsNotNull() {
            addCriterion("operator_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameEqualTo(String value) {
            addCriterion("operator_user_name =", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameNotEqualTo(String value) {
            addCriterion("operator_user_name <>", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameGreaterThan(String value) {
            addCriterion("operator_user_name >", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_user_name >=", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameLessThan(String value) {
            addCriterion("operator_user_name <", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameLessThanOrEqualTo(String value) {
            addCriterion("operator_user_name <=", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameLike(String value) {
            addCriterion("operator_user_name like", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameNotLike(String value) {
            addCriterion("operator_user_name not like", value, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameIn(List<String> values) {
            addCriterion("operator_user_name in", values, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameNotIn(List<String> values) {
            addCriterion("operator_user_name not in", values, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameBetween(String value1, String value2) {
            addCriterion("operator_user_name between", value1, value2, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorUserNameNotBetween(String value1, String value2) {
            addCriterion("operator_user_name not between", value1, value2, "operatorUserName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameIsNull() {
            addCriterion("operator_first_name is null");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameIsNotNull() {
            addCriterion("operator_first_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameEqualTo(String value) {
            addCriterion("operator_first_name =", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameNotEqualTo(String value) {
            addCriterion("operator_first_name <>", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameGreaterThan(String value) {
            addCriterion("operator_first_name >", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_first_name >=", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameLessThan(String value) {
            addCriterion("operator_first_name <", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameLessThanOrEqualTo(String value) {
            addCriterion("operator_first_name <=", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameLike(String value) {
            addCriterion("operator_first_name like", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameNotLike(String value) {
            addCriterion("operator_first_name not like", value, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameIn(List<String> values) {
            addCriterion("operator_first_name in", values, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameNotIn(List<String> values) {
            addCriterion("operator_first_name not in", values, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameBetween(String value1, String value2) {
            addCriterion("operator_first_name between", value1, value2, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorFirstNameNotBetween(String value1, String value2) {
            addCriterion("operator_first_name not between", value1, value2, "operatorFirstName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameIsNull() {
            addCriterion("operator_middle_name is null");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameIsNotNull() {
            addCriterion("operator_middle_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameEqualTo(String value) {
            addCriterion("operator_middle_name =", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameNotEqualTo(String value) {
            addCriterion("operator_middle_name <>", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameGreaterThan(String value) {
            addCriterion("operator_middle_name >", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_middle_name >=", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameLessThan(String value) {
            addCriterion("operator_middle_name <", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameLessThanOrEqualTo(String value) {
            addCriterion("operator_middle_name <=", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameLike(String value) {
            addCriterion("operator_middle_name like", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameNotLike(String value) {
            addCriterion("operator_middle_name not like", value, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameIn(List<String> values) {
            addCriterion("operator_middle_name in", values, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameNotIn(List<String> values) {
            addCriterion("operator_middle_name not in", values, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameBetween(String value1, String value2) {
            addCriterion("operator_middle_name between", value1, value2, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorMiddleNameNotBetween(String value1, String value2) {
            addCriterion("operator_middle_name not between", value1, value2, "operatorMiddleName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameIsNull() {
            addCriterion("operator_last_name is null");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameIsNotNull() {
            addCriterion("operator_last_name is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameEqualTo(String value) {
            addCriterion("operator_last_name =", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameNotEqualTo(String value) {
            addCriterion("operator_last_name <>", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameGreaterThan(String value) {
            addCriterion("operator_last_name >", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameGreaterThanOrEqualTo(String value) {
            addCriterion("operator_last_name >=", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameLessThan(String value) {
            addCriterion("operator_last_name <", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameLessThanOrEqualTo(String value) {
            addCriterion("operator_last_name <=", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameLike(String value) {
            addCriterion("operator_last_name like", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameNotLike(String value) {
            addCriterion("operator_last_name not like", value, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameIn(List<String> values) {
            addCriterion("operator_last_name in", values, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameNotIn(List<String> values) {
            addCriterion("operator_last_name not in", values, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameBetween(String value1, String value2) {
            addCriterion("operator_last_name between", value1, value2, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorLastNameNotBetween(String value1, String value2) {
            addCriterion("operator_last_name not between", value1, value2, "operatorLastName");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressIsNull() {
            addCriterion("operator_home_address is null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressIsNotNull() {
            addCriterion("operator_home_address is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressEqualTo(String value) {
            addCriterion("operator_home_address =", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressNotEqualTo(String value) {
            addCriterion("operator_home_address <>", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressGreaterThan(String value) {
            addCriterion("operator_home_address >", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("operator_home_address >=", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressLessThan(String value) {
            addCriterion("operator_home_address <", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressLessThanOrEqualTo(String value) {
            addCriterion("operator_home_address <=", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressLike(String value) {
            addCriterion("operator_home_address like", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressNotLike(String value) {
            addCriterion("operator_home_address not like", value, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressIn(List<String> values) {
            addCriterion("operator_home_address in", values, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressNotIn(List<String> values) {
            addCriterion("operator_home_address not in", values, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressBetween(String value1, String value2) {
            addCriterion("operator_home_address between", value1, value2, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddressNotBetween(String value1, String value2) {
            addCriterion("operator_home_address not between", value1, value2, "operatorHomeAddress");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2IsNull() {
            addCriterion("operator_home_address2 is null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2IsNotNull() {
            addCriterion("operator_home_address2 is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2EqualTo(String value) {
            addCriterion("operator_home_address2 =", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2NotEqualTo(String value) {
            addCriterion("operator_home_address2 <>", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2GreaterThan(String value) {
            addCriterion("operator_home_address2 >", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("operator_home_address2 >=", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2LessThan(String value) {
            addCriterion("operator_home_address2 <", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2LessThanOrEqualTo(String value) {
            addCriterion("operator_home_address2 <=", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2Like(String value) {
            addCriterion("operator_home_address2 like", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2NotLike(String value) {
            addCriterion("operator_home_address2 not like", value, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2In(List<String> values) {
            addCriterion("operator_home_address2 in", values, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2NotIn(List<String> values) {
            addCriterion("operator_home_address2 not in", values, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2Between(String value1, String value2) {
            addCriterion("operator_home_address2 between", value1, value2, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeAddress2NotBetween(String value1, String value2) {
            addCriterion("operator_home_address2 not between", value1, value2, "operatorHomeAddress2");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityIsNull() {
            addCriterion("operator_home_city is null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityIsNotNull() {
            addCriterion("operator_home_city is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityEqualTo(String value) {
            addCriterion("operator_home_city =", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityNotEqualTo(String value) {
            addCriterion("operator_home_city <>", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityGreaterThan(String value) {
            addCriterion("operator_home_city >", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityGreaterThanOrEqualTo(String value) {
            addCriterion("operator_home_city >=", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityLessThan(String value) {
            addCriterion("operator_home_city <", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityLessThanOrEqualTo(String value) {
            addCriterion("operator_home_city <=", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityLike(String value) {
            addCriterion("operator_home_city like", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityNotLike(String value) {
            addCriterion("operator_home_city not like", value, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityIn(List<String> values) {
            addCriterion("operator_home_city in", values, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityNotIn(List<String> values) {
            addCriterion("operator_home_city not in", values, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityBetween(String value1, String value2) {
            addCriterion("operator_home_city between", value1, value2, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeCityNotBetween(String value1, String value2) {
            addCriterion("operator_home_city not between", value1, value2, "operatorHomeCity");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateIsNull() {
            addCriterion("operator_home_state is null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateIsNotNull() {
            addCriterion("operator_home_state is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateEqualTo(String value) {
            addCriterion("operator_home_state =", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateNotEqualTo(String value) {
            addCriterion("operator_home_state <>", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateGreaterThan(String value) {
            addCriterion("operator_home_state >", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateGreaterThanOrEqualTo(String value) {
            addCriterion("operator_home_state >=", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateLessThan(String value) {
            addCriterion("operator_home_state <", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateLessThanOrEqualTo(String value) {
            addCriterion("operator_home_state <=", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateLike(String value) {
            addCriterion("operator_home_state like", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateNotLike(String value) {
            addCriterion("operator_home_state not like", value, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateIn(List<String> values) {
            addCriterion("operator_home_state in", values, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateNotIn(List<String> values) {
            addCriterion("operator_home_state not in", values, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateBetween(String value1, String value2) {
            addCriterion("operator_home_state between", value1, value2, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeStateNotBetween(String value1, String value2) {
            addCriterion("operator_home_state not between", value1, value2, "operatorHomeState");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipIsNull() {
            addCriterion("operator_home_zip is null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipIsNotNull() {
            addCriterion("operator_home_zip is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipEqualTo(String value) {
            addCriterion("operator_home_zip =", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipNotEqualTo(String value) {
            addCriterion("operator_home_zip <>", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipGreaterThan(String value) {
            addCriterion("operator_home_zip >", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipGreaterThanOrEqualTo(String value) {
            addCriterion("operator_home_zip >=", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipLessThan(String value) {
            addCriterion("operator_home_zip <", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipLessThanOrEqualTo(String value) {
            addCriterion("operator_home_zip <=", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipLike(String value) {
            addCriterion("operator_home_zip like", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipNotLike(String value) {
            addCriterion("operator_home_zip not like", value, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipIn(List<String> values) {
            addCriterion("operator_home_zip in", values, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipNotIn(List<String> values) {
            addCriterion("operator_home_zip not in", values, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipBetween(String value1, String value2) {
            addCriterion("operator_home_zip between", value1, value2, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andOperatorHomeZipNotBetween(String value1, String value2) {
            addCriterion("operator_home_zip not between", value1, value2, "operatorHomeZip");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operator
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table operator
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}