package com.zil.cherubim.model;

public class Operator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_user_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_first_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorFirstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_middle_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorMiddleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_last_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorLastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_home_address
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorHomeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_home_address2
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorHomeAddress2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_home_city
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorHomeCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_home_state
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorHomeState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_home_zip
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String operatorHomeZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.email
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.password
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.status
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.id
     *
     * @return the value of operator.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.id
     *
     * @param id the value for operator.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_id
     *
     * @return the value of operator.operator_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_id
     *
     * @param operatorId the value for operator.operator_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_user_name
     *
     * @return the value of operator.operator_user_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorUserName() {
        return operatorUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_user_name
     *
     * @param operatorUserName the value for operator.operator_user_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorUserName(String operatorUserName) {
        this.operatorUserName = operatorUserName == null ? null : operatorUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_first_name
     *
     * @return the value of operator.operator_first_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorFirstName() {
        return operatorFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_first_name
     *
     * @param operatorFirstName the value for operator.operator_first_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorFirstName(String operatorFirstName) {
        this.operatorFirstName = operatorFirstName == null ? null : operatorFirstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_middle_name
     *
     * @return the value of operator.operator_middle_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorMiddleName() {
        return operatorMiddleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_middle_name
     *
     * @param operatorMiddleName the value for operator.operator_middle_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorMiddleName(String operatorMiddleName) {
        this.operatorMiddleName = operatorMiddleName == null ? null : operatorMiddleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_last_name
     *
     * @return the value of operator.operator_last_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorLastName() {
        return operatorLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_last_name
     *
     * @param operatorLastName the value for operator.operator_last_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorLastName(String operatorLastName) {
        this.operatorLastName = operatorLastName == null ? null : operatorLastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_home_address
     *
     * @return the value of operator.operator_home_address
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorHomeAddress() {
        return operatorHomeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_home_address
     *
     * @param operatorHomeAddress the value for operator.operator_home_address
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorHomeAddress(String operatorHomeAddress) {
        this.operatorHomeAddress = operatorHomeAddress == null ? null : operatorHomeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_home_address2
     *
     * @return the value of operator.operator_home_address2
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorHomeAddress2() {
        return operatorHomeAddress2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_home_address2
     *
     * @param operatorHomeAddress2 the value for operator.operator_home_address2
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorHomeAddress2(String operatorHomeAddress2) {
        this.operatorHomeAddress2 = operatorHomeAddress2 == null ? null : operatorHomeAddress2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_home_city
     *
     * @return the value of operator.operator_home_city
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorHomeCity() {
        return operatorHomeCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_home_city
     *
     * @param operatorHomeCity the value for operator.operator_home_city
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorHomeCity(String operatorHomeCity) {
        this.operatorHomeCity = operatorHomeCity == null ? null : operatorHomeCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_home_state
     *
     * @return the value of operator.operator_home_state
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorHomeState() {
        return operatorHomeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_home_state
     *
     * @param operatorHomeState the value for operator.operator_home_state
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorHomeState(String operatorHomeState) {
        this.operatorHomeState = operatorHomeState == null ? null : operatorHomeState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.operator_home_zip
     *
     * @return the value of operator.operator_home_zip
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOperatorHomeZip() {
        return operatorHomeZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.operator_home_zip
     *
     * @param operatorHomeZip the value for operator.operator_home_zip
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOperatorHomeZip(String operatorHomeZip) {
        this.operatorHomeZip = operatorHomeZip == null ? null : operatorHomeZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.email
     *
     * @return the value of operator.email
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.email
     *
     * @param email the value for operator.email
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.password
     *
     * @return the value of operator.password
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.password
     *
     * @param password the value for operator.password
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operator.status
     *
     * @return the value of operator.status
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operator.status
     *
     * @param status the value for operator.status
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}