package com.zil.cherubim.model;

public class PlayerCharacter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_character.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_character.player_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_character.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer characterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_character.id
     *
     * @return the value of player_character.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_character.id
     *
     * @param id the value for player_character.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_character.player_id
     *
     * @return the value of player_character.player_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_character.player_id
     *
     * @param playerId the value for player_character.player_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_character.character_id
     *
     * @return the value of player_character.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getCharacterId() {
        return characterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_character.character_id
     *
     * @param characterId the value for player_character.character_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setCharacterId(Integer characterId) {
        this.characterId = characterId;
    }
}