package com.zil.cherubim.model;

import java.util.Date;

public class Player {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.player_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.player_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String playerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.email
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.password
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.birthdate
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Date birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.gender
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.player_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String playerImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.is_facebook_acct
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String isFacebookAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player.status
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.id
     *
     * @return the value of player.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.id
     *
     * @param id the value for player.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.player_id
     *
     * @return the value of player.player_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.player_id
     *
     * @param playerId the value for player.player_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.player_name
     *
     * @return the value of player.player_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.player_name
     *
     * @param playerName the value for player.player_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.email
     *
     * @return the value of player.email
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.email
     *
     * @param email the value for player.email
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.password
     *
     * @return the value of player.password
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.password
     *
     * @param password the value for player.password
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.birthdate
     *
     * @return the value of player.birthdate
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Date getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.birthdate
     *
     * @param birthdate the value for player.birthdate
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.gender
     *
     * @return the value of player.gender
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.gender
     *
     * @param gender the value for player.gender
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.player_image
     *
     * @return the value of player.player_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getPlayerImage() {
        return playerImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.player_image
     *
     * @param playerImage the value for player.player_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setPlayerImage(String playerImage) {
        this.playerImage = playerImage == null ? null : playerImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.is_facebook_acct
     *
     * @return the value of player.is_facebook_acct
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getIsFacebookAcct() {
        return isFacebookAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.is_facebook_acct
     *
     * @param isFacebookAcct the value for player.is_facebook_acct
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setIsFacebookAcct(String isFacebookAcct) {
        this.isFacebookAcct = isFacebookAcct == null ? null : isFacebookAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player.status
     *
     * @return the value of player.status
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player.status
     *
     * @param status the value for player.status
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}