package com.zil.cherubim.model;

public class RaceSkill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race_skill.race_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer raceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer skillId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race_skill.id
     *
     * @return the value of race_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race_skill.id
     *
     * @param id the value for race_skill.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race_skill.race_id
     *
     * @return the value of race_skill.race_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getRaceId() {
        return raceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race_skill.race_id
     *
     * @param raceId the value for race_skill.race_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setRaceId(Integer raceId) {
        this.raceId = raceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race_skill.skill_id
     *
     * @return the value of race_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getSkillId() {
        return skillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race_skill.skill_id
     *
     * @param skillId the value for race_skill.skill_id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillId(Integer skillId) {
        this.skillId = skillId;
    }
}