package com.zil.cherubim.model;

public class Race {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race.race_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String raceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race.race_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String raceDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race.race_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String raceImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column race.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race.id
     *
     * @return the value of race.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race.id
     *
     * @param id the value for race.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race.race_name
     *
     * @return the value of race.race_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getRaceName() {
        return raceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race.race_name
     *
     * @param raceName the value for race.race_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setRaceName(String raceName) {
        this.raceName = raceName == null ? null : raceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race.race_description
     *
     * @return the value of race.race_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getRaceDescription() {
        return raceDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race.race_description
     *
     * @param raceDescription the value for race.race_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setRaceDescription(String raceDescription) {
        this.raceDescription = raceDescription == null ? null : raceDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race.race_image
     *
     * @return the value of race.race_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getRaceImage() {
        return raceImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race.race_image
     *
     * @param raceImage the value for race.race_image
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setRaceImage(String raceImage) {
        this.raceImage = raceImage == null ? null : raceImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column race.is_available
     *
     * @return the value of race.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column race.is_available
     *
     * @param isAvailable the value for race.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setIsAvailable(Integer isAvailable) {
        this.isAvailable = isAvailable;
    }
}