package com.zil.cherubim.model;

import java.util.ArrayList;
import java.util.List;

public class RaceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public RaceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRaceNameIsNull() {
            addCriterion("race_name is null");
            return (Criteria) this;
        }

        public Criteria andRaceNameIsNotNull() {
            addCriterion("race_name is not null");
            return (Criteria) this;
        }

        public Criteria andRaceNameEqualTo(String value) {
            addCriterion("race_name =", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameNotEqualTo(String value) {
            addCriterion("race_name <>", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameGreaterThan(String value) {
            addCriterion("race_name >", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameGreaterThanOrEqualTo(String value) {
            addCriterion("race_name >=", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameLessThan(String value) {
            addCriterion("race_name <", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameLessThanOrEqualTo(String value) {
            addCriterion("race_name <=", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameLike(String value) {
            addCriterion("race_name like", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameNotLike(String value) {
            addCriterion("race_name not like", value, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameIn(List<String> values) {
            addCriterion("race_name in", values, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameNotIn(List<String> values) {
            addCriterion("race_name not in", values, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameBetween(String value1, String value2) {
            addCriterion("race_name between", value1, value2, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceNameNotBetween(String value1, String value2) {
            addCriterion("race_name not between", value1, value2, "raceName");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionIsNull() {
            addCriterion("race_description is null");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionIsNotNull() {
            addCriterion("race_description is not null");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionEqualTo(String value) {
            addCriterion("race_description =", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionNotEqualTo(String value) {
            addCriterion("race_description <>", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionGreaterThan(String value) {
            addCriterion("race_description >", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("race_description >=", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionLessThan(String value) {
            addCriterion("race_description <", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionLessThanOrEqualTo(String value) {
            addCriterion("race_description <=", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionLike(String value) {
            addCriterion("race_description like", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionNotLike(String value) {
            addCriterion("race_description not like", value, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionIn(List<String> values) {
            addCriterion("race_description in", values, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionNotIn(List<String> values) {
            addCriterion("race_description not in", values, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionBetween(String value1, String value2) {
            addCriterion("race_description between", value1, value2, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceDescriptionNotBetween(String value1, String value2) {
            addCriterion("race_description not between", value1, value2, "raceDescription");
            return (Criteria) this;
        }

        public Criteria andRaceImageIsNull() {
            addCriterion("race_image is null");
            return (Criteria) this;
        }

        public Criteria andRaceImageIsNotNull() {
            addCriterion("race_image is not null");
            return (Criteria) this;
        }

        public Criteria andRaceImageEqualTo(String value) {
            addCriterion("race_image =", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageNotEqualTo(String value) {
            addCriterion("race_image <>", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageGreaterThan(String value) {
            addCriterion("race_image >", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageGreaterThanOrEqualTo(String value) {
            addCriterion("race_image >=", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageLessThan(String value) {
            addCriterion("race_image <", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageLessThanOrEqualTo(String value) {
            addCriterion("race_image <=", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageLike(String value) {
            addCriterion("race_image like", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageNotLike(String value) {
            addCriterion("race_image not like", value, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageIn(List<String> values) {
            addCriterion("race_image in", values, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageNotIn(List<String> values) {
            addCriterion("race_image not in", values, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageBetween(String value1, String value2) {
            addCriterion("race_image between", value1, value2, "raceImage");
            return (Criteria) this;
        }

        public Criteria andRaceImageNotBetween(String value1, String value2) {
            addCriterion("race_image not between", value1, value2, "raceImage");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNull() {
            addCriterion("is_available is null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNotNull() {
            addCriterion("is_available is not null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableEqualTo(Integer value) {
            addCriterion("is_available =", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotEqualTo(Integer value) {
            addCriterion("is_available <>", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThan(Integer value) {
            addCriterion("is_available >", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_available >=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThan(Integer value) {
            addCriterion("is_available <", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThanOrEqualTo(Integer value) {
            addCriterion("is_available <=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIn(List<Integer> values) {
            addCriterion("is_available in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotIn(List<Integer> values) {
            addCriterion("is_available not in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableBetween(Integer value1, Integer value2) {
            addCriterion("is_available between", value1, value2, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotBetween(Integer value1, Integer value2) {
            addCriterion("is_available not between", value1, value2, "isAvailable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table race
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}