package com.zil.cherubim.model;

import java.util.ArrayList;
import java.util.List;

public class SkillsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public SkillsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSkillNameIsNull() {
            addCriterion("skill_name is null");
            return (Criteria) this;
        }

        public Criteria andSkillNameIsNotNull() {
            addCriterion("skill_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkillNameEqualTo(String value) {
            addCriterion("skill_name =", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameNotEqualTo(String value) {
            addCriterion("skill_name <>", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameGreaterThan(String value) {
            addCriterion("skill_name >", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameGreaterThanOrEqualTo(String value) {
            addCriterion("skill_name >=", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameLessThan(String value) {
            addCriterion("skill_name <", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameLessThanOrEqualTo(String value) {
            addCriterion("skill_name <=", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameLike(String value) {
            addCriterion("skill_name like", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameNotLike(String value) {
            addCriterion("skill_name not like", value, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameIn(List<String> values) {
            addCriterion("skill_name in", values, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameNotIn(List<String> values) {
            addCriterion("skill_name not in", values, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameBetween(String value1, String value2) {
            addCriterion("skill_name between", value1, value2, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillNameNotBetween(String value1, String value2) {
            addCriterion("skill_name not between", value1, value2, "skillName");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionIsNull() {
            addCriterion("skill_description is null");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionIsNotNull() {
            addCriterion("skill_description is not null");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionEqualTo(String value) {
            addCriterion("skill_description =", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionNotEqualTo(String value) {
            addCriterion("skill_description <>", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionGreaterThan(String value) {
            addCriterion("skill_description >", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("skill_description >=", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionLessThan(String value) {
            addCriterion("skill_description <", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionLessThanOrEqualTo(String value) {
            addCriterion("skill_description <=", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionLike(String value) {
            addCriterion("skill_description like", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionNotLike(String value) {
            addCriterion("skill_description not like", value, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionIn(List<String> values) {
            addCriterion("skill_description in", values, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionNotIn(List<String> values) {
            addCriterion("skill_description not in", values, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionBetween(String value1, String value2) {
            addCriterion("skill_description between", value1, value2, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andSkillDescriptionNotBetween(String value1, String value2) {
            addCriterion("skill_description not between", value1, value2, "skillDescription");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelIsNull() {
            addCriterion("required_level is null");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelIsNotNull() {
            addCriterion("required_level is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelEqualTo(Integer value) {
            addCriterion("required_level =", value, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelNotEqualTo(Integer value) {
            addCriterion("required_level <>", value, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelGreaterThan(Integer value) {
            addCriterion("required_level >", value, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("required_level >=", value, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelLessThan(Integer value) {
            addCriterion("required_level <", value, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelLessThanOrEqualTo(Integer value) {
            addCriterion("required_level <=", value, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelIn(List<Integer> values) {
            addCriterion("required_level in", values, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelNotIn(List<Integer> values) {
            addCriterion("required_level not in", values, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelBetween(Integer value1, Integer value2) {
            addCriterion("required_level between", value1, value2, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andRequiredLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("required_level not between", value1, value2, "requiredLevel");
            return (Criteria) this;
        }

        public Criteria andIsParentIsNull() {
            addCriterion("is_parent is null");
            return (Criteria) this;
        }

        public Criteria andIsParentIsNotNull() {
            addCriterion("is_parent is not null");
            return (Criteria) this;
        }

        public Criteria andIsParentEqualTo(Byte value) {
            addCriterion("is_parent =", value, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentNotEqualTo(Byte value) {
            addCriterion("is_parent <>", value, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentGreaterThan(Byte value) {
            addCriterion("is_parent >", value, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_parent >=", value, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentLessThan(Byte value) {
            addCriterion("is_parent <", value, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentLessThanOrEqualTo(Byte value) {
            addCriterion("is_parent <=", value, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentIn(List<Byte> values) {
            addCriterion("is_parent in", values, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentNotIn(List<Byte> values) {
            addCriterion("is_parent not in", values, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentBetween(Byte value1, Byte value2) {
            addCriterion("is_parent between", value1, value2, "isParent");
            return (Criteria) this;
        }

        public Criteria andIsParentNotBetween(Byte value1, Byte value2) {
            addCriterion("is_parent not between", value1, value2, "isParent");
            return (Criteria) this;
        }

        public Criteria andParentSkillIsNull() {
            addCriterion("parent_skill is null");
            return (Criteria) this;
        }

        public Criteria andParentSkillIsNotNull() {
            addCriterion("parent_skill is not null");
            return (Criteria) this;
        }

        public Criteria andParentSkillEqualTo(Integer value) {
            addCriterion("parent_skill =", value, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillNotEqualTo(Integer value) {
            addCriterion("parent_skill <>", value, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillGreaterThan(Integer value) {
            addCriterion("parent_skill >", value, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_skill >=", value, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillLessThan(Integer value) {
            addCriterion("parent_skill <", value, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillLessThanOrEqualTo(Integer value) {
            addCriterion("parent_skill <=", value, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillIn(List<Integer> values) {
            addCriterion("parent_skill in", values, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillNotIn(List<Integer> values) {
            addCriterion("parent_skill not in", values, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillBetween(Integer value1, Integer value2) {
            addCriterion("parent_skill between", value1, value2, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andParentSkillNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_skill not between", value1, value2, "parentSkill");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNull() {
            addCriterion("is_available is null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIsNotNull() {
            addCriterion("is_available is not null");
            return (Criteria) this;
        }

        public Criteria andIsAvailableEqualTo(Byte value) {
            addCriterion("is_available =", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotEqualTo(Byte value) {
            addCriterion("is_available <>", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThan(Byte value) {
            addCriterion("is_available >", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_available >=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThan(Byte value) {
            addCriterion("is_available <", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableLessThanOrEqualTo(Byte value) {
            addCriterion("is_available <=", value, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableIn(List<Byte> values) {
            addCriterion("is_available in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotIn(List<Byte> values) {
            addCriterion("is_available not in", values, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableBetween(Byte value1, Byte value2) {
            addCriterion("is_available between", value1, value2, "isAvailable");
            return (Criteria) this;
        }

        public Criteria andIsAvailableNotBetween(Byte value1, Byte value2) {
            addCriterion("is_available not between", value1, value2, "isAvailable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skills
     *
     * @mbggenerated do_not_delete_during_merge Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}