package com.zil.cherubim.model;

public class Skills {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.skill_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String skillName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.skill_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private String skillDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.required_level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer requiredLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.is_parent
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Byte isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.parent_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer parentSkill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column skills.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Byte isAvailable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.id
     *
     * @return the value of skills.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.id
     *
     * @param id the value for skills.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.skill_name
     *
     * @return the value of skills.skill_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getSkillName() {
        return skillName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.skill_name
     *
     * @param skillName the value for skills.skill_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillName(String skillName) {
        this.skillName = skillName == null ? null : skillName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.skill_description
     *
     * @return the value of skills.skill_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public String getSkillDescription() {
        return skillDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.skill_description
     *
     * @param skillDescription the value for skills.skill_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setSkillDescription(String skillDescription) {
        this.skillDescription = skillDescription == null ? null : skillDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.required_level
     *
     * @return the value of skills.required_level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getRequiredLevel() {
        return requiredLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.required_level
     *
     * @param requiredLevel the value for skills.required_level
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setRequiredLevel(Integer requiredLevel) {
        this.requiredLevel = requiredLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.is_parent
     *
     * @return the value of skills.is_parent
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Byte getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.is_parent
     *
     * @param isParent the value for skills.is_parent
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setIsParent(Byte isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.parent_skill
     *
     * @return the value of skills.parent_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getParentSkill() {
        return parentSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.parent_skill
     *
     * @param parentSkill the value for skills.parent_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setParentSkill(Integer parentSkill) {
        this.parentSkill = parentSkill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column skills.is_available
     *
     * @return the value of skills.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Byte getIsAvailable() {
        return isAvailable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column skills.is_available
     *
     * @param isAvailable the value for skills.is_available
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setIsAvailable(Byte isAvailable) {
        this.isAvailable = isAvailable;
    }
}