package com.zil.cherubim.model;

public class Stats {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stats.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stats.stat_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer statName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stats.stat_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    private Integer statDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stats.id
     *
     * @return the value of stats.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stats.id
     *
     * @param id the value for stats.id
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stats.stat_name
     *
     * @return the value of stats.stat_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getStatName() {
        return statName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stats.stat_name
     *
     * @param statName the value for stats.stat_name
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setStatName(Integer statName) {
        this.statName = statName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stats.stat_description
     *
     * @return the value of stats.stat_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public Integer getStatDescription() {
        return statDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stats.stat_description
     *
     * @param statDescription the value for stats.stat_description
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    public void setStatDescription(Integer statDescription) {
        this.statDescription = statDescription;
    }
}