package com.zil.cherubim.mapper;

import com.zil.cherubim.model.Character;
import com.zil.cherubim.model.CharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<Character> selectByExample(CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    Character selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") Character record, @Param("example") CharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(Character record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(Character record);    
}