package com.zil.cherubim.mapper;

import com.zil.cherubim.model.CharacterStats;
import com.zil.cherubim.model.CharacterStatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterStatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(CharacterStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(CharacterStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(CharacterStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(CharacterStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<CharacterStats> selectByExample(CharacterStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    CharacterStats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") CharacterStats record, @Param("example") CharacterStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") CharacterStats record, @Param("example") CharacterStatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(CharacterStats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(CharacterStats record);
}