package com.zil.cherubim.mapper;

import com.zil.cherubim.model.CharacterSkill;
import com.zil.cherubim.model.CharacterSkillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(CharacterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(CharacterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(CharacterSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(CharacterSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<CharacterSkill> selectByExample(CharacterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    CharacterSkill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") CharacterSkill record, @Param("example") CharacterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") CharacterSkill record, @Param("example") CharacterSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(CharacterSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(CharacterSkill record);
}