package com.zil.cherubim.mapper;

import com.zil.cherubim.model.CharacterJob;
import com.zil.cherubim.model.CharacterJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(CharacterJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(CharacterJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(CharacterJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(CharacterJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<CharacterJob> selectByExample(CharacterJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    CharacterJob selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") CharacterJob record, @Param("example") CharacterJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") CharacterJob record, @Param("example") CharacterJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(CharacterJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_job
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(CharacterJob record);
}