package com.zil.cherubim.mapper;

import com.zil.cherubim.model.CharacterRace;
import com.zil.cherubim.model.CharacterRaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CharacterRaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(CharacterRaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(CharacterRaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(CharacterRace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(CharacterRace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<CharacterRace> selectByExample(CharacterRaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    CharacterRace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") CharacterRace record, @Param("example") CharacterRaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") CharacterRace record, @Param("example") CharacterRaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(CharacterRace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table character_race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(CharacterRace record);
}