package com.zil.cherubim.mapper;

import com.zil.cherubim.model.JobsSkill;
import com.zil.cherubim.model.JobsSkillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobsSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(JobsSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(JobsSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(JobsSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(JobsSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<JobsSkill> selectByExample(JobsSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    JobsSkill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") JobsSkill record, @Param("example") JobsSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") JobsSkill record, @Param("example") JobsSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(JobsSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jobs_skill
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(JobsSkill record);
}