package com.zil.cherubim.mapper;

import com.zil.cherubim.model.PlayerCharacter;
import com.zil.cherubim.model.PlayerCharacterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PlayerCharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(PlayerCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(PlayerCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(PlayerCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(PlayerCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<PlayerCharacter> selectByExample(PlayerCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    PlayerCharacter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") PlayerCharacter record, @Param("example") PlayerCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") PlayerCharacter record, @Param("example") PlayerCharacterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(PlayerCharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_character
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(PlayerCharacter record);
}