package com.zil.cherubim.mapper;

import com.zil.cherubim.model.Race;
import com.zil.cherubim.model.RaceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(RaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(RaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(Race record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(Race record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<Race> selectByExample(RaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    Race selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") Race record, @Param("example") RaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") Race record, @Param("example") RaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(Race record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table race
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(Race record);
}