package com.zil.cherubim.mapper;

import com.zil.cherubim.model.Skills;
import com.zil.cherubim.model.SkillsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkillsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(Skills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(Skills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<Skills> selectByExample(SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    Skills selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") Skills record, @Param("example") SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") Skills record, @Param("example") SkillsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(Skills record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table skills
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(Skills record);
}