package com.zil.cherubim.mapper;

import com.zil.cherubim.model.Stats;
import com.zil.cherubim.model.StatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int countByExample(StatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByExample(StatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insert(Stats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int insertSelective(Stats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    List<Stats> selectByExample(StatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    Stats selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExampleSelective(@Param("record") Stats record, @Param("example") StatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByExample(@Param("record") Stats record, @Param("example") StatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKeySelective(Stats record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stats
     *
     * @mbggenerated Sat Dec 26 21:53:38 CST 2015
     */
    int updateByPrimaryKey(Stats record);
}